import type { Note, CreateNoteInput, UpdateNoteInput } from "@/lib/types/note";
import { supabaseRequest, encodeUserId } from "@/lib/supabase/client";

// Needed to determine specific error types (400, 404, etc.) for user-friendly messages
function getErrorStatus(error: unknown): number {
  if (error && typeof error === "object" && "status" in error) {
    return (error as { status: number }).status;
  }
  return 0;
}

export async function fetchAllNotes(userId: string): Promise<Note[]> {
  const encodedUserId = encodeUserId(userId);
  // Filter by user_id for data isolation (API requirement)
  const endpoint = `/notes?user_id=eq.${encodedUserId}&order=created_at.desc`;
  
  try {
    const notes = await supabaseRequest<Note[]>(endpoint);
    // Ensure we always return an array (defensive programming)
    return Array.isArray(notes) ? notes : [];
  } catch (error) {
    throw new Error(`Failed to fetch notes: ${error instanceof Error ? error.message : "Unknown error"}`);
  }
}

// Fetches a single note by ID, validates it belongs to the user
export async function fetchNoteById(
  id: string,
  userId: string
): Promise<Note> {
  const encodedUserId = encodeUserId(userId);
  // Filter by both id and user_id for security (prevents access to other users' notes)
  const endpoint = `/notes?id=eq.${id}&user_id=eq.${encodedUserId}`;

  try {
    // Supabase always returns array, even for single-item queries
    const notes = await supabaseRequest<Note[]>(endpoint);

    if (!Array.isArray(notes) || notes.length === 0) {
      throw new Error(`Note with id ${id} not found`);
    }

    return notes[0];
  } catch (error) {
    // Preserve "not found" errors for better error handling upstream
    if (error instanceof Error && error.message.includes("not found")) {
      throw error;
    }
    throw new Error(`Failed to fetch note: ${error instanceof Error ? error.message : "Unknown error"}`);
  }
}

export async function createNote(note: CreateNoteInput): Promise<Note> {
  const endpoint = "/notes";

  try {
    const createdNote = await supabaseRequest<Note>(endpoint, {
      method: "POST",
      body: note,
    });

    // Validate server response (id is auto-generated by Supabase)
    if (!createdNote || !createdNote.id) {
      throw new Error("Failed to create note: Invalid response from server");
    }

    return createdNote;
  } catch (error) {
    const status = getErrorStatus(error);
    
    // 400 = validation error (missing fields, exceeds length limits: title 100, content 5000)
    if (status === 400) {
      throw new Error("Invalid note data. Please check title and content.");
    }

    throw new Error(
      `Failed to create note: ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }
}

export async function updateNote(
  id: string,
  userId: string,
  updates: UpdateNoteInput
): Promise<Note> {
  const encodedUserId = encodeUserId(userId);
  const endpoint = `/notes?id=eq.${id}&user_id=eq.${encodedUserId}`;

  // API requires modified_at timestamp in ISO 8601 format
  const updatePayload = {
    ...updates,
    modified_at: new Date().toISOString(),
  };

  try {
    // Supabase may return array or single object depending on query params
    const response = await supabaseRequest<Note | Note[]>(endpoint, {
      method: "PATCH",
      body: updatePayload,
    });

    // Handle both response formats (array from query params, object from direct response)
    const updatedNote = Array.isArray(response) ? response[0] : response;

    if (!updatedNote || !updatedNote.id) {
      throw new Error("Failed to update note: Invalid response from server");
    }

    return updatedNote;
  } catch (error) {
    const status = getErrorStatus(error);

    // 404 = note doesn't exist or belongs to different user
    if (status === 404) {
      throw new Error(`Note with id ${id} not found`);
    }

    // 400 = validation error (exceeds limits or invalid data)
    if (status === 400) {
      throw new Error("Invalid update data. Please check your changes.");
    }

    throw new Error(
      `Failed to update note: ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }
}

export async function deleteNote(id: string, userId: string): Promise<void> {
  const encodedUserId = encodeUserId(userId);
  const endpoint = `/notes?id=eq.${id}&user_id=eq.${encodedUserId}`;

  try {
    // DELETE returns 204 No Content (handled in supabaseRequest)
    await supabaseRequest<void>(endpoint, {
      method: "DELETE",
    });
  } catch (error) {
    const status = getErrorStatus(error);

    // 404 = note doesn't exist or belongs to different user
    if (status === 404) {
      throw new Error(`Note with id ${id} not found`);
    }

    throw new Error(
      `Failed to delete note: ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }
}

