import type { Note, CreateNoteInput, UpdateNoteInput } from "@/lib/types/note";
import { supabaseRequest, encodeUserId } from "@/lib/supabase/client";

function getErrorStatus(error: unknown): number {
  if (error && typeof error === "object" && "status" in error) {
    return (error as { status: number }).status;
  }
  return 0;
}

/**
 * Fetches all notes for a specific user from Supabase.
 * Notes are ordered by creation date (newest first).
 * 
 * @param userId - The user's email address
 * @returns Promise resolving to an array of notes (empty array if none found)
 * @throws Error if the API request fails
 */
export async function fetchAllNotes(userId: string): Promise<Note[]> {
  const encodedUserId = encodeUserId(userId);
  const endpoint = `/notes?user_id=eq.${encodedUserId}&order=created_at.desc`;
  
  try {
    const notes = await supabaseRequest<Note[]>(endpoint);
    return Array.isArray(notes) ? notes : [];
  } catch (error) {
    throw new Error(
      `Failed to fetch notes: ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }
}

/**
 * Fetches a single note by ID, ensuring it belongs to the specified user.
 * This prevents unauthorized access to other users' notes.
 * 
 * @param id - The note's unique identifier (UUID)
 * @param userId - The user's email address
 * @returns Promise resolving to the note object
 * @throws Error if the note is not found or the API request fails
 */
export async function fetchNoteById(
  id: string,
  userId: string
): Promise<Note> {
  const encodedUserId = encodeUserId(userId);
  const endpoint = `/notes?id=eq.${id}&user_id=eq.${encodedUserId}`;

  try {
    const notes = await supabaseRequest<Note[]>(endpoint);

    if (!Array.isArray(notes) || notes.length === 0) {
      throw new Error(`Note with id ${id} not found`);
    }

    return notes[0];
  } catch (error) {
    if (error instanceof Error && error.message.includes("not found")) {
      throw error;
    }
    throw new Error(
      `Failed to fetch note: ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }
}

/**
 * Creates a new note in Supabase.
 * The note ID, created_at, and modified_at are automatically generated by the server.
 * 
 * @param note - Note data (user_id, title, content)
 * @returns Promise resolving to the created note with server-generated fields
 * @throws Error if validation fails (400) or the API request fails
 */
export async function createNote(note: CreateNoteInput): Promise<Note> {
  const endpoint = "/notes";

  try {
    const response = await supabaseRequest<Note | Note[]>(endpoint, {
      method: "POST",
      body: note,
    });

    const createdNote = Array.isArray(response) ? response[0] : response;

    if (!createdNote || !createdNote.id) {
      if (process.env.NODE_ENV === 'development') {
        console.error("Invalid create note response:", response);
      }
      throw new Error("Failed to create note: Invalid response from server");
    }

    return createdNote;
  } catch (error) {
    const status = getErrorStatus(error);
    
    if (status === 400) {
      throw new Error(
        "Invalid note data. Title must be 100 characters or less, and content must be 5000 characters or less."
      );
    }

    throw new Error(
      `Failed to create note: ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }
}

/**
 * Updates an existing note in Supabase.
 * Automatically updates the modified_at timestamp to the current time.
 * 
 * @param id - The note's unique identifier (UUID)
 * @param userId - The user's email address (for authorization)
 * @param updates - Partial note data to update (title and/or content)
 * @returns Promise resolving to the updated note
 * @throws Error if the note is not found (404), validation fails (400), or the API request fails
 */
export async function updateNote(
  id: string,
  userId: string,
  updates: UpdateNoteInput
): Promise<Note> {
  const encodedUserId = encodeUserId(userId);
  const endpoint = `/notes?id=eq.${id}&user_id=eq.${encodedUserId}`;

  const updatePayload = {
    ...updates,
    modified_at: new Date().toISOString(),
  };

  try {
    const response = await supabaseRequest<Note | Note[]>(endpoint, {
      method: "PATCH",
      body: updatePayload,
    });

    const updatedNote = Array.isArray(response) ? response[0] : response;

    if (!updatedNote || !updatedNote.id) {
      throw new Error("Failed to update note: Invalid response from server");
    }

    return updatedNote;
  } catch (error) {
    const status = getErrorStatus(error);

    if (status === 404) {
      throw new Error(`Note with id ${id} not found`);
    }

    if (status === 400) {
      throw new Error(
        "Invalid update data. Title must be 100 characters or less, and content must be 5000 characters or less."
      );
    }

    throw new Error(
      `Failed to update note: ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }
}

/**
 * Deletes a note from Supabase.
 * This operation is permanent and cannot be undone.
 * 
 * @param id - The note's unique identifier (UUID)
 * @param userId - The user's email address (for authorization)
 * @returns Promise resolving to void on success
 * @throws Error if the note is not found (404) or the API request fails
 */
export async function deleteNote(id: string, userId: string): Promise<void> {
  const encodedUserId = encodeUserId(userId);
  const endpoint = `/notes?id=eq.${id}&user_id=eq.${encodedUserId}`;

  try {
    await supabaseRequest<void>(endpoint, {
      method: "DELETE",
    });
  } catch (error) {
    const status = getErrorStatus(error);

    if (status === 404) {
      throw new Error(`Note with id ${id} not found`);
    }

    throw new Error(
      `Failed to delete note: ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }
}

