/**
 * Note interface matching the Supabase data model
 * 
 * This represents a note in the system with all required fields.
 * The id is auto-generated by the server as a UUID.
 * Timestamps are in ISO 8601 format.
 */
export interface Note {
  /** Unique identifier (UUID, auto-generated by server) */
  id: string;
  
  /** User ID (email address) - used for data isolation */
  user_id: string;
  
  /** Note title (required, max 100 characters) */
  title: string;
  
  /** Note content (required, max 5000 characters) */
  content: string;
  
  /** ISO 8601 timestamp of when the note was created */
  created_at: string;
  
  /** ISO 8601 timestamp of when the note was last modified */
  modified_at: string;
}

/**
 * Type for creating a new note (omits server-generated fields)
 */
export type CreateNoteInput = Omit<Note, 'id' | 'created_at' | 'modified_at'>;

/**
 * Type for updating an existing note (all fields optional except id)
 */
export type UpdateNoteInput = Partial<Pick<Note, 'title' | 'content'>> & {
  modified_at: string; // Always update modified_at when updating
};

